### ISSUE TITLE
Add curves for animations

### ISSUE THREAD

**Issue by AbhayVAshokan** [aagarwal1012/Animated-Text-Kit#100]
**Is your feature request related to a problem? Please describe.**
The TypewriterAnimatedTextKit has ```bounce``` curve by default. That is, after completely writing a line of text, it shakes for less than a second.

**Describe the solution you'd like**
Add a curves parameter where the developer can specify animation curves like ```easeIn```, ```bounce```, ```decelerate```, etc.

**Describe alternatives you've considered**
I used ```TyperAnimatedTextKit``` instead. It does not have the ```bounce``` curve as default.

**Comment by SirusCodes** [comment]
@AadumKhor @aagarwal1012 @hemilpanchiwala this seems a nice issue to me. I know that many of the animated text widgets might work as expected but we can give devs option if they want to do trial and error? What are your thoughts? I can work on this as a final PR for hacktoberfest.

**Comment by AadumKhor** [comment]
@SirusCodes you can start working on this. I think we had someone make a PR for this feature before but that was never completed.

**Comment by SirusCodes** [comment]
@AadumKhor I will start to work on it from Saturday 👍

**Comment by SirusCodes** [comment]
@AadumKhor I don't think it would be a good idea as all the animations looks kinda weird😅

**Comment by AadumKhor** [comment]
@SirusCodes no issue. If possible share some screen recordings so that we have a better idea.

**Comment by SirusCodes** [comment]
![Animation](https://user-images.githubusercontent.com/50910066/95198468-ec240700-07f8-11eb-812b-a54491b2338e.gif)
This is with Curves.bounceIn...Idk now its looking cool to me😅😅

**Comment by AadumKhor** [comment]
Looks a bit janky don't you think? I mean if all agree then I have no problems in proceeding.

**Comment by SirusCodes** [comment]
Ya a bit... @aagarwal1012 @hemilpanchiwala what are your views?

**Comment by AbhayVAshokan** [comment]
Closing #100 by referring #183
