### ISSUE TITLE
Dancing Text

### ISSUE THREAD

**Issue by SirusCodes** [aagarwal1012/Animated-Text-Kit#106]
Hello,
I have made an animation using text I thought making a package of it, but someone suggested me to add it to this package. Also suggest me some other name as I have named it very vaguely😅

![dancing text](https://user-images.githubusercontent.com/50910066/93119851-23af0000-f6e0-11ea-92ae-174b4e74304a.gif)

**Comment by aagarwal1012** [comment]
@AadumKhor @hemilpanchiwala, can you guys please look into this issue?

**Comment by AadumKhor** [comment]
@aagarwal1012 sure. @SirusCodes excellent work first of all, this would be a good addition to the package. Since it is a "wave" you can name it around that keyword. I'll check if you have made a PR, please update the docs as well while you are at it.

**Comment by SirusCodes** [comment]
Thanks @AadumKhor @hemilpanchiwala for your appreciation 😊. I would name it as WavyText and as I'm not free until 20th I will start working on it after that.

**Comment by SirusCodes** [comment]
Hey @AadumKhor @hemilpanchiwala @aagarwal1012 today I started to work on it and realized that in each Animation we are passing a list. I thought of keep this as a single text animation. Should I follow the convention or make it a single Text?

**Comment by hemilpanchiwala** [comment]
@SirusCodes, I think you should proceed with the list as it provides more general use (even satisfying the single Text purpose).

**Comment by SirusCodes** [comment]
Okk👍 @hemilpanchiwala

**Comment by SirusCodes** [comment]
Hey I'm having some difficulties to port my [work](https://codepen.io/siruscodes/pen/XWdzoKa) to the text list style can anyone help me? 
@hemilpanchiwala @aagarwal1012 @AadumKhor
