### ISSUE TITLE
How to create animation karaoke lyrics

### ISSUE THREAD

**Issue by vickyvu0684** [aagarwal1012/Animated-Text-Kit#110]
Hello everyone,

Can you give me an example of a text effect like in the picture.(animation for karaoke lyrics)
Thanks so much

![E13B3590-0B37-4A65-B671-E8955C8856E4](https://user-images.githubusercontent.com/9211638/93832291-7cae0380-fc9f-11ea-9768-495dfdbb1fd3.png)

**Comment by vickyvu0684** [comment]
Please help me.

**Comment by AadumKhor** [comment]
Since this is not a part of the package I am not sure why this issue was made. Please have a look at `CustomPainter` documentation, more specifically `TextPainter` for some ideas.
