### ISSUE TITLE
Emoji make exception in TyperAnimatedTextKit

### ISSUE THREAD

**Issue by eunjin3786** [aagarwal1012/Animated-Text-Kit#118]
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'dart:ui/painting.dart': Failed assertion: line 3968: '<optimized out>': is not true.

**Comment by awhitford** [comment]
Can you please provide some sample code and a stack trace?  The above assertion is not very much to go on.

**Comment by eunjin3786** [comment]
@awhitford 

Thankyou 👍

```swift
class SettingsWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return Padding(
        padding: EdgeInsets.all(10),
        child: Center(
          child: TyperAnimatedTextKit(
            text: ["hello world ☺️👍🍥️"],
            isRepeatingAnimation: true,
            speed: Duration(milliseconds: 60)
          ),
        )
    );
  }
}
```






════════ Exception caught by rendering library ═════════════════════════════════════════════════════
'dart:ui/painting.dart': Failed assertion: line 3968: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TyperAnimatedTextKit file:///Users/kakao/Documents/onion_family/lib/widget/main/settings_widget.dart:14:18
The following RenderObject was being processed when the exception was fired: RenderParagraph#a695f relayoutBoundary=up3
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=394.0, 0.0<=h<=792.0)
  size: Size(114.0, 27.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    inherit: false
    color: label(*color = Color(0xff000000)*, darkColor = Color(0xffffffff), resolved by: Builder)
      debugLabel: label
      color: Color(0xff000000)
      darkColor: Color(0xffffffff)
      last resolved: Builder
    family: .SF Pro Text
    size: 17.0
    letterSpacing: -0.4
    decoration: TextDecoration.none
    "hello world ☺️👍?"
RenderObject: RenderParagraph#a695f relayoutBoundary=up3
  parentData: <none> (can use size)
  constraints: BoxConstraints(0.0<=w<=394.0, 0.0<=h<=792.0)
  size: Size(114.0, 27.0)
  textAlign: start
  textDirection: ltr
  softWrap: wrapping at box width
  overflow: clip
  locale: en_US
  maxLines: unlimited
  text: TextSpan
    inherit: false
    color: label(*color = Color(0xff000000)*, darkColor = Color(0xffffffff), resolved by: Builder)
      debugLabel: label
      color: Color(0xff000000)
      darkColor: Color(0xffffffff)
      last resolved: Builder
    family: .SF Pro Text
    size: 17.0
    letterSpacing: -0.4
    decoration: TextDecoration.none
    "hello world ☺️👍?"
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by awhitford** [comment]
This looks like the offending widget:
https://github.com/aagarwal1012/Animated-Text-Kit/blob/fa78a437ff8b3b0aa7febc5202c709330c4f23bf/lib/src/typer.dart#L145-L149

I see this message:
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown during performLayout():
flutter: Invalid argument(s): string is not well-formed UTF-16
flutter:
flutter: The relevant error-causing widget was:
flutter:   Text
flutter:   file:///Users/anthony/flutter/.pub-cache/hosted/pub.dartlang.org/animated_text_kit-2.3.0/lib/src/typer.dart:145:26
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ParagraphBuilder.addText (dart:ui/text.dart:2178:7)
flutter: #1      TextSpan.build (package:flutter/src/painting/text_span.dart:208:15)
flutter: #2      TextPainter.layout (package:flutter/src/painting/text_painter.dart:560:14)
flutter: #3      RenderParagraph._layoutText (package:flutter/src/rendering/paragraph.dart:497:18)
flutter: #4      RenderParagraph._layoutTextWithConstraints (package:flutter/src/rendering/paragraph.dart:520:5)
```
This looks like a known issue: https://github.com/dart-lang/sdk/issues/35798

This reminds me of the [Flutter 1.22 announcement](https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f) where they mentioned the [characters package](https://pub.dev/packages/characters).

The _String Length_ of ```'☺️👍🍥️'``` is not 3, but actually 7. However, it is only 3 _Characters_.

The solution is to rework the widget to use the new Characters package, rather than use `String.substring`.

**Comment by awhitford** [comment]
Note that the Typewriter has the same flaw and will also need to be fixed, but let's wait for the Typer fix to be reviewed first.

**Comment by awhitford** [comment]
PR #122 addresses Typewriter.
