### ISSUE TITLE
Can use SingleTickerProviderStateMixin

### ISSUE THREAD

**Issue by SirusCodes** [aagarwal1012/Animated-Text-Kit#119]
We can use SingleTickerProviderStateMixin in almost all of animations.

**Current implementation**
We are calling setting `_controller` and `Animation` each time
```dart
_controller = AnimationController(
    duration: _duration,
    vsync: this,
);
```

**Better implementation**
We set `_controller` and `Animation` in `initState` an call forward each time
```dart
_controller.forward(from:  0.0);
```

This will reduce the calls which we are making in each cycle. Using SingleTickerProviderStateMixin is more efficient than TickerProviderStateMixin.

If you want I would like to collaborate on this.

**Comment by awhitford** [comment]
Are you willing to submit a PR?

**Comment by SirusCodes** [comment]
Yup I can do that

**Comment by SirusCodes** [comment]
Hey I have made the changes but I'm getting `AnimationController methods should not be used after calling dispose.` error when I'm changing the animation view. All the disposes are in proper position.

**Comment by awhitford** [comment]
@SirusCodes Which class?  Looking at Fade, as an example, `_controller?.dispose();` is only called during the `dispose` method, so that seems fine.  A stack trace may be helpful.

**Comment by SirusCodes** [comment]
Sorry I should have provided this earlier only.
```console
E/flutter (11494): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 456 pos 7: '_ticker != null': AnimationController.forward() called after AnimationController.dispose()
E/flutter (11494): AnimationController methods should not be used after calling dispose.
E/flutter (11494): #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:46:39))
E/flutter (11494): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:36:5))
E/flutter (11494): #2      AnimationController.forward 
package:flutter/…/animation/animation_controller.dart:456
E/flutter (11494): #3      _RotatingTextState._nextAnimation 
package:animated_text_kit/src/rotate.dart:259
E/flutter (11494): #4      _rootRun  (dart:async/zone.dart:1182:47))
E/flutter (11494): #5      _CustomZone.run  (dart:async/zone.dart:1093:19))
E/flutter (11494): #6      _CustomZone.runGuarded  (dart:async/zone.dart:997:7))
E/flutter (11494): #7      _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23))
E/flutter (11494): #8      _rootRun  (dart:async/zone.dart:1190:13))
E/flutter (11494): #9      _CustomZone.run  (dart:async/zone.dart:1093:19))
E/flutter (11494): #10     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23))
E/flutter (11494): #11     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15))
E/flutter (11494): #12     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19))
E/flutter (11494): #13     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5))
E/flutter (11494): #14     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12))
E/flutter (11494):

```

**Comment by awhitford** [comment]
Since I do not see your changes, it is challenging to imagine that the issue may be.

Maybe you can debug it by putting a breakpoint on `AnimationController.dispose` and seeing when it is called.  It should only be called when the widget is being disposed, but maybe there is something unexpected?

Also, I assume that the `AnimationController` is created in the `State.initState` method and then disposed in the `State.dispose` method, as prescribed?

**Comment by SirusCodes** [comment]
Yes I have properly initialised and disposed AnimationController. Will try to add breakpoints and figure out what is the problem tomorrow 👍

**Comment by SirusCodes** [comment]
I guess I got the issue.
When I change the screen the AnimationController is disposed but Timer is waiting to complete and when it completes it calls the _next function which calls _controller.forward().

I need to stop timer or something else when dispose is called.

**Comment by awhitford** [comment]
I just submitted PR #121 for Fade, based on issue #98.  It sounds like you have a similar issue.

**Comment by SirusCodes** [comment]
Yes, timer in all the animations are not handled properly...it would be great if you can do that and after your PR is merge I would create my PR.

**Comment by SirusCodes** [comment]
You can expect a PR by tonight 👍

**Comment by aagarwal1012** [comment]
#124 fixes this issue!
