### ISSUE TITLE
TextAlign Property

### ISSUE THREAD

**Issue by JotaFerreira** [aagarwal1012/Animated-Text-Kit#13]
Is support possible?

**Comment by aagarwal1012** [comment]
@JotaFerreira, You have to do it yourself by putting the `Animated Text Widget` in the `Container Widget` or any other widget and then align it.
Hope you understand this thing.

**Comment by JotaFerreira** [comment]
I tried this, but I could not, so I "solved" by inserting empty spaces in the text to be centralized.

`  static final List<String> music6 = [
    "Do nosso peito a aurea offerta",
    "    Do valor de todos nós    ",
    "  Há de florir forte e certa  ",
    "   De um canto a rutila voz   "
  ];`

**Comment by aagarwal1012** [comment]
@JotaFerreira 
Oh! Now I understand your issue, surely work upon it.
@salihgueler, can you have a look at this issue?

**Comment by salihgueler** [comment]
When I have the opportunity I will take a look into it @aagarwal1012 :)

**Comment by aagarwal1012** [comment]
#19 refrenced
