### ISSUE TITLE
[docs] Improve documentation and add dartdoc

### ISSUE THREAD

**Issue by aagarwal1012** [aagarwal1012/Animated-Text-Kit#147]
- [x] Check/add/update documentation for all public classes and method in the package. Documentation issue address by the Flutter community are mentioned below:
```grovy
  FadeAnimatedTextKit: fade.dart:5:1
  createState: fade.dart:107:3
  TextLiquidFill: text_liquid_fill.dart:4:1
  createState: text_liquid_fill.dart:71:3
  WavePainter: text_liquid_fill.dart:167:1
  paint: text_liquid_fill.dart:183:3
  shouldRepaint: text_liquid_fill.dart:209:3
  TypewriterAnimatedTextKit: typewriter.dart:6:1
  createState: typewriter.dart:106:3
  ColorizeAnimatedTextKit: colorize.dart:4:1
  createState: colorize.dart:91:3
  RotateAnimatedTextKit: rotate.dart:4:1
  createState: rotate.dart:111:3
  TyperAnimatedTextKit: typer.dart:6:1
  createState: typer.dart:91:3
  WavyAnimatedTextKit: wavy.dart:5:1
  createState: wavy.dart:62:3
  ScaleAnimatedTextKit: scale.dart:5:1
  createState: scale.dart:114:3
```

- [ ] Add [dartdoc](https://pub.dev/packages/dartdoc) and host the HTML documentation on github pages.

cc: @awhitford

**Comment by aagarwal1012** [comment]
@awhitford, Flutter team uses this tool to score the package for the flutter favorite program -- https://github.com/kf6gpe/dart-flutter-favorite.

**Comment by awhitford** [comment]
Note that documentation for `createState` methods should not be necessary -- looks like a 🐞  https://github.com/kf6gpe/dart-flutter-favorite/issues/11

Is hosting `dartdoc` on github pages necessary when `pub.dev` hosts the _API reference_?  Is any other Flutter package doing that?

**Comment by aagarwal1012** [comment]
@awhitford, hosting `dartdoc` is just a suggestion for us to make better documentation, it is not necessary for now.

**Comment by awhitford** [comment]
Generating `dartdoc` locally is trivial, and you get the API on `pub.dev` from a `publish`, so I do not recommend adding the complexity of `gh-pages` because I expect people will simply go to `pub.dev` (or rely on their IDE).

**Comment by aagarwal1012** [comment]
I agree with your argument -- let's close this issue for now.
