### ISSUE TITLE
AlignmentGeometry is unused

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#153]
I noticed that many classes have a property like this:

https://github.com/aagarwal1012/Animated-Text-Kit/blob/002484cb5aa3a50d3cb378e937aece2e0497beff/lib/src/typer.dart#L45-L48

However, it is not used.

As a result, I recommend removing it to avoid confusion.

This impacts:
* Colorize
* Fade
* Scale
* Typer
* Typerwriter

**Comment by awhitford** [comment]
@aagarwal1012 Can we get away with removing this all at once?  Or should we leave a `@deprecated` parameter for a release to warn people?  (Since it was not used, I'm leaning towards just removing it altogether.)

**Comment by aagarwal1012** [comment]
@awhitford, let's remove this unused parameter and create a new release.

**Comment by awhitford** [comment]
This parameter is used only by `RotateAnimatedTextKit`.  I'll submit a PR in a second.
