### ISSUE TITLE
Confirm Fade Intervals

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#156]
Consider this code:
https://github.com/aagarwal1012/Animated-Text-Kit/blob/498be509695cf37d9108836b52d65572e9d960b3/lib/src/fade.dart#L173-L185

@aagarwal1012 Can you please confirm that the 0.8 (line 183) is _intentionally_ not 0.5 (like line 176)?

(It is just asymmetrical to me and makes me wonder if this is a typo or intentional.) 🤔

**Comment by aagarwal1012** [comment]
@awhitford, I am not sure of this one, probably I have added this one for the sake smoothness of the animation, but I think you are right, it should be symmetrical.

**Comment by awhitford** [comment]
I experimented with adjusting these values, but I really couldn't notice a difference.  It may be a very subtle "bug."

**Comment by awhitford** [comment]
In retrospect, I suspect this is intentional so that the text hangs around for a while after it fades in before it fades out.

**Comment by aagarwal1012** [comment]
@awhitford, that's correct!
