### ISSUE TITLE
Slide in from right and Slide out to left or vice versa

### ISSUE THREAD

**Issue by anderscheow** [aagarwal1012/Animated-Text-Kit#16]
Would you provide a new animated text kit which serve following purpose:
_           _           A
_           A           _ (stop for a duration)
A           _           B
_           B           _ (stop for a duration)
B           _           C
... and so on

**Comment by aagarwal1012** [comment]
@anderscheow, If you had a gif image of the animation then we can surely add this into the project section.

**Comment by anderscheow** [comment]
https://github.com/hust201010701/XDanmuku
It could be something like this. It can be multiple or single text, with right to left or left to right animation.
