### ISSUE TITLE
Accept List of Widgets instead of List of String for more flexibility

### ISSUE THREAD

**Issue by anderscheow** [aagarwal1012/Animated-Text-Kit#17]
I would suggest if the List<String> could change to List<Widget>, then it would be great. Since by using widget provide better flexibility.

**Comment by aagarwal1012** [comment]
@anderscheow,  Actually I already had this issue in my mind at the time of making this package but cannot find a way to implement that while using different animation and text rendering.
Thanks for raising the issue, we will surely look upon this issue 👍
