### ISSUE TITLE
[Proposal] Add onFinishedBeforePause Parameter

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [aagarwal1012/Animated-Text-Kit#174]
**Describe the bug**
I'm running an animation after another one ends, but I want it to start immediately after the last animation is complete. I have a 1 second pause time and that runs before it calls my function and I can't remove that pause.

**Expected behavior**
The function is called immediately after the last animation is complete, rather than animate > pause > animate > pause >onFinished.
 animated_text_kit: ^3.0.1

**Comment by ThinkDigitalSoftware** [comment]
I believe this is the `onNextBeforePause` method.

**Comment by awhitford** [comment]
Why don't you simply add a pause to your `onFinished` callback?  Like use [Future.delayed](https://api.dart.dev/stable/2.10.4/dart-async/Future/Future.delayed.html) to pause then trigger [addPostFrameCallback](https://api.flutter.dev/flutter/scheduler/SchedulerBinding/addPostFrameCallback.html)?

**Comment by ThinkDigitalSoftware** [comment]
Because on finished runs too late. For example, with the typewriter, I want to trigger the onFinished as in the Frame that follows the last letter, not the last letter, plus the pause, then the onFinished

**Comment by awhitford** [comment]
Oh, I thought you were saying that you wanted to ADD a pause -- not REMOVE the pause.

**Comment by ThinkDigitalSoftware** [comment]
This is a better idea. and yes, it would work for me

**Comment by awhitford** [comment]
@ThinkDigitalSoftware Just to be clear...  You want the pause, just NOT for the LAST one, right?  Because you can modify the `pause` to be zero (or near zero).

**Comment by ThinkDigitalSoftware** [comment]
Correct. I'm trying to do a chain of animations and the widget doesn't allow me to call a callback **immediately** after. There's a delay I can't avoid.

**Comment by ThinkDigitalSoftware** [comment]
Correct. I'm trying to do a chain of animations and the widget doesn't allow me to call a callback **immediately** after. There's a delay I can't avoid. Imagine if I wanted to type 2 words in in 2 separate widgets and I wanted It to look like 1 long word. It would pause at the end of word 1 and wait before It started. I want to be able to trigger something at the same time as the next letter would have animated in.

**Comment by awhitford** [comment]
Thanks for clarifying...  I am truly wondering whether there should be a final pause.  I mean, _what's the point?_ It reminds me of a `String.join` method -- you don't end up with a _separator_ at the _end_.

Rather than this (currently):
* Animation1 -> pause -> Animation2 -> pause -> Animation 3 -> pause -> onFinished

Wouldn't dropping the final be more _naturally expected_?:
* Animation1 -> pause -> Animation2 -> pause -> Animation 3 -> onFinished

@aagarwal1012 What do you think about dropping the last pause?

Having said that, I think your discovery about `onNextBeforePause` was on point -- and that is available now.
That callback is triggered _before_ the pause, and there is even a flag that tells you when you are on the _last_ item.

I'd like to avoid creating a new flag like `pauseOnLast` -- there are already so many flags; it can get confusing.  And they are difficult to name...  _"Last what?"_ -- _Last for every repeat?  Last for only the final repeat?_ 😩 

In action...
```dart
                AnimatedTextKit(
                  animatedTexts: [
                    RotateAnimatedText(
                      'Ready',
                      textStyle: textStyle,
                    ),
                    RotateAnimatedText(
                      'Set',
                      textStyle: textStyle,
                    ),
                    RotateInAnimatedText(
                      'Go!',
                      textStyle: textStyle,
                    )
                  ],
                  onTap: onTap,
                  isRepeatingAnimation: false,
                  onNextBeforePause: (_, isLast) {
                    if (isLast) {
                      print("And we're off!");
                    }
                  },
                ),
```

**Comment by ThinkDigitalSoftware** [comment]
Dropping the last pause is perfect.

**Comment by SirusCodes** [comment]
I think making any changes in `onNextBeforePause` will affect existing users and might might confuse them. Making another method would be a viable option.

**Comment by awhitford** [comment]
@SirusCodes To be clear, I did not change `onNextBeforePause`, nor am I proposing making such a change.  I am pointing out that using it solves @ThinkDigitalSoftware's delay problem.  The `isLast` flag is the secret-sauce.

**Comment by SirusCodes** [comment]
Yes but this might force others to add this flag even if they don't have any need for it🤔

**Comment by awhitford** [comment]
The `isLast` flag is already there.

**Comment by SirusCodes** [comment]
Oh I thought you are proposing this change sorry 😅 then it's fine.
