### ISSUE TITLE
Migrating to null safety

### ISSUE THREAD

**Issue by SirusCodes** [aagarwal1012/Animated-Text-Kit#184]
After null safety coming to beta we should migrate this package to null safety. But how we push new updates to the package after migration?

**Comment by awhitford** [comment]
All 3 Flutter channels are currently supported: stable, beta, and dev.

If we upgrade it for _null safety_ now (with _stable_ using Dart 2.10.x), we need to upgrade the Dart version and dependencies to their null-safety versions, and then that will cause _divergence_ because new versions of the library will not be available on the stable channel.  (Pub takes into account the environment constraint and won't give users the newest version of your package that requires the latest dart version.)

I've been _holding back_ on _null-safety_ for this reason.

**Comment by aagarwal1012** [comment]
@awhitford @SirusCodes 
We can prepare the package for the `null safety` then we can do a pre-release on `pub.dev`, check this for more instructions, [Publishing prereleases](https://dart.dev/tools/pub/publishing#publishing-prereleases). Many packages are doing the same thing, once the flutter `stable` channel fully supports the null safety, then we can do a stable release.
Many packages are doing the same thing, check [Mobx](https://pub.dev/packages/mobx/versions) for reference.

**Comment by SirusCodes** [comment]
I'm not asking for a stable release for null safety. We can support null safety and just bring that to stable, once null safety comes to stable in flutter.

**Comment by SirusCodes** [comment]
> @awhitford @SirusCodes 
> We can prepare the package for the `null safety` then we can do a pre-release on `pub.dev`, check this for more instructions, [Publishing prereleases](https://dart.dev/tools/pub/publishing#publishing-prereleases). Many packages are doing the same thing, once the flutter `stable` channel fully supports the null safety, then we can do a stable release.
> Many packages are doing the same thing, check [Mobx](https://pub.dev/packages/mobx/versions) for reference.

How they are managing the updates? Because we need to keep up with the updates in both versions.

**Comment by aagarwal1012** [comment]
> How they are managing the updates?

We can maintain a `beta` branch for null-safety related updates in the code.

**Comment by awhitford** [comment]
It is just potentially double the work...
* We would need to create a _null-safety_ branch, which we would publish the _pre-release_ version from.  That branch can no longer build on _stable_.
* Any changes to _master_ would need to be manually merged into the _null-safety_ branch too.

If we do this _now_, I suggest that we aim to _freeze_ the master branch to minimize the merging headache.  If that idea troubles you, then I suggest we hold off until the next _stable_ release.

Updating this package to null-safety is not a lot of work.  I think it could be done in about an hour.  I'm not concerned about that migration -- it is the ongoing maintenance issues that concerns me.  If this goes on for a week, it is not risky, but if it goes on until March, then that is riskier.

**Comment by aagarwal1012** [comment]
I agree with @awhitford, let's hold this thing until the next stable release of flutter.

**Comment by SirusCodes** [comment]
Yes this is what was concerning me. Let's wait for the 3.3.2021 event maybe that would be the good time to do it.

**Comment by SirusCodes** [comment]
Ig this is the time now...
https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by SirusCodes** [comment]
@awhitford @aagarwal1012 What are your views??

**Comment by aagarwal1012** [comment]
@SirusCodes Sure, let's introduce null safety in the code.

**Comment by SirusCodes** [comment]
4.0.0 version?

**Comment by aagarwal1012** [comment]
Yes, `v4.0.0` will work.
