### ISSUE TITLE
Colorize doesn't work on web iOS 14 using flutter 1.25

### ISSUE THREAD

**Issue by EagleSigma** [aagarwal1012/Animated-Text-Kit#188]
**Describe the bug**
The Colorize text works perfectly in desktop browser but turns text to black color and no Colorize effect.

**To Reproduce**
Run flutter web build app with any Colorized text on iOS 14. The text turns black (originally white) and no effects.

**Expected behavior**
Colorize works on desktop but not on iOS web browser.  Chrome or Safari.

**Screenshots**

**Flutter:**
 - 1.25.0-8.2.pre 
 - channel beta - web

**Dart:**
 - Dart 2.12.0 (build 2.12.0-133.2.beta)
 - 
**Additional context**
I'm new with flutter. It's possible I'm just missing some kind of switch that will tell the package it's running on a mobile web browser.  Thank you for the awesome work.

**Comment by aagarwal1012** [comment]
@EagleSigma, can you please confirm if this issue still persists?

**Comment by SirusCodes** [comment]
Ig this is also a flutter related issue, not sure if it is fixed but seems like it is fixed already by looking at the reference commits in https://github.com/flutter/flutter/issues/48438.

**Comment by awhitford** [comment]
PR #222 shows that Colorize seems to be working fine now.
