### ISSUE TITLE
Document setState/text workaround

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#198]
Issue #27 outlines a relatively common problem where changing the `text` doesn't update the widget.  There is a workaround solution (specify a `key` that changes based on the `text`), but it should be documented in the `README`.

I'd also like to understand _better_ what is going on, and _why_ this is necessary.

**Comment by SirusCodes** [comment]
What I feel this because of this issue...
We are using `StatefulWidget` for each animation when `setState` is called the widget tree rebuilds itself but it only checks for `runtimeType`. But if key is passed it will check for that as well.

You can look at [this](https://www.youtube.com/watch?v=kn0EOS-ZiIc) video by flutter team for better understanding.

**Comment by subhangi2731** [comment]
can you assign this to me?

**Comment by aagarwal1012** [comment]
@subhangi2731, you can work on this issue as well.

**Comment by Ruhika1417** [comment]
hi @aagarwal1012 I would like to work on it if its not solved yet....Could you pls let me know if you can assign this to me?!

**Comment by aagarwal1012** [comment]
@Ruhika1417, sure you can work on it. It's a minimal issue related to documentation, so I think there should not be an issue with that.

**Comment by Khushi-24** [comment]
@aagarwal1012 Is the issue resolved? If not can I work on this?

**Comment by aagarwal1012** [comment]
@Khushi-24 this is still available, you can work on this.

**Comment by Khushi-24** [comment]
Sorry for the inconvenience. Due to some issues, I am unable to work on this.

**Comment by Mohitmadhav** [comment]
@awhitford can I work on this issue?

**Comment by SirusCodes** [comment]
@Mohitmadhav you can start working on it and open a PR.
