### ISSUE TITLE
Implement AutoSizeText

### ISSUE THREAD

**Issue by anderscheow** [aagarwal1012/Animated-Text-Kit#20]
In some of the use cases, you may want to let the "text" to fit in a single line without truncating. So I would suggest to use [auto_size_text](https://github.com/leisim/auto_size_text) to auto scale the text based on the constraint.

**Comment by aagarwal1012** [comment]
We don't need this issue, because using auto_size_text will generate an extra dependency on the package.

**Comment by flipflop133** [comment]
Is there a way tough to use autosizetext with this package?
