### ISSUE TITLE
[feat] Prepare animated text kit flutter web app for demo 

### ISSUE THREAD

**Issue by aagarwal1012** [aagarwal1012/Animated-Text-Kit#201]
### Description
Rather than suggesting everyone install the `example` app to experience Animated Text Kit in action, it will be better to host the example app on Github Pages using single page flutter web application.
Other suggestions are highly welcomed.

### Resources
- https://flutter.dev/web
- https://medium.com/@zonble/use-github-pages-to-host-your-flutter-web-app-as-an-example-of-your-flutter-package-cb7b5b726eb1
- https://maheshmnj.medium.com/deploying-your-flutter-webapp-to-github-pages-111ff9e5cbc9

**Comment by SirusCodes** [comment]
We can reuse the current `example app` and give a sidebar to select animation 🤔

**Comment by itsIapetus** [comment]
I would like to work on this as a part of GSSoC, could you please assign it to me and guide me with the process?

**Comment by SirusCodes** [comment]
@itsIapetus you can continue with this...

**Comment by SirusCodes** [comment]
You can start start working on `/example` and make something like [flutter/sample/web_dashboard](https://flutter.github.io/samples/web_dashboard.html)

**Comment by awhitford** [comment]
Please be aware that the current `smoke_test` iterates through the `example` pages to exercise each animation.  The test does not _need_ to use the `example` -- but we presently have a respectable 95% code coverage, and it would be shame to see that drop.  So, if the `example` exercise is removed from the `smoke_test`, let's just make sure that other testing is added to exercise the code.

**Comment by awhitford** [comment]
This [tweet](https://twitter.com/luke_pighetti/status/1370333429737390081) has a [gist](https://gist.github.com/lukepighetti/dca8d731aa95adfa86fd01b0c76222d5) that shows how to publish a _flutter web build_ to [Firebase Hosting Preview Channels](https://firebase.google.com/docs/hosting/manage-hosting-resources).

**Comment by aagarwal1012** [comment]
@awhitford, if we are going to use firebase hosting, then I can try to set up this one.

**Comment by SirusCodes** [comment]
We can use gh pages as well🤔

**Comment by aagarwal1012** [comment]
#222 should be good for now.
