### ISSUE TITLE
Functionality similar to AnimatedSwitcher

### ISSUE THREAD

**Issue by modulovalue** [aagarwal1012/Animated-Text-Kit#21]
**Is your feature request related to a problem? Please describe.**
I was hoping that this package would let me animate between text similar to what `AnimatedSwitcher` does.

**Describe the solution you'd like**
It would be amazing if I could provide a string (or a stream of strings) and when that string changes an animation would be triggered to flawlessly transition between the current and previous string.

**Describe alternatives you've considered**
An AnimatedSwitcher could achieve some of the effects with a custom `transitionBuilder & layoutBuilder` but this package seems to be more flexible.

**Additional context**
Would such functionality even fit into the design of this library?

@aagarwal1012 feel free to close this issue if something like that is beyond the scope of what you wanted this library to be.

**Comment by aagarwal1012** [comment]
@modulovalue, actually my motive of creating this package is to add different text animations and also involve the flutter community to contribute to this project.
