### ISSUE TITLE
update contributing.md

### ISSUE THREAD

**Issue by khareyash05** [aagarwal1012/Animated-Text-Kit#214]
Hey! I would like to add the following in contributing.md
1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream

**Comment by SirusCodes** [comment]
Do we really need this? If we want to add such things, we can just add a link in CONTRIBUTING.md

**Comment by khareyash05** [comment]
@SirusCodes I think we really need because it will act as a one stop shop for open source contributions and also if necessary will be able to work offline which we cant do with just links. A proper documentation will increase the reputation level of our repo

**Comment by awhitford** [comment]
📚  **GitHub already provides some great documentation**:
 * [GitHub Guides](https://guides.github.com/)
 * [GitHub Documentation](https://docs.github.com/)

While I am sympathetic to being a helpful resource for newbies, it is unrealistic to expect every project outline the basics for folks.

**A project should only be concerned with outlining _project specific_ guidance.**
