### ISSUE TITLE
Update README.md file

### ISSUE THREAD

**Issue by aditi1403** [aagarwal1012/Animated-Text-Kit#219]
I have made some minor grammatical edits to the README.md file. Kindly refer to PR #218.

**Comment by awhitford** [comment]
Is this intended for GSSOC credit?

**Comment by aditi1403** [comment]
> Is this intended for GSSOC credit?

yes

**Comment by aagarwal1012** [comment]
@aditi1403, sorry to say, but we don't accept PRs related to grammatical changes, we are not English scholars, and we are okay with it.
