### ISSUE TITLE
Prevent creation of so many widgets and animation variables

### ISSUE THREAD

**Issue by anderscheow** [aagarwal1012/Animated-Text-Kit#22]
It's clear that by creating exact number of text widget and animation variable based on the length of text is the fastest way of creating the desire animation. But memory consumption would increase based on the length of text.

So, I would suggest that just use two animations and two text widget to switch between different text, it could drastically reduce the memory consumption and increase in performance.

**Comment by aagarwal1012** [comment]
Yeah we can work upon this issue. Thanks :+1:
