### ISSUE TITLE
Add `TextLiquidFill` to example app

### ISSUE THREAD

**Issue by aagarwal1012** [aagarwal1012/Animated-Text-Kit#231]
I noticed recently that the example app doesn't contain `TextLiquidFill Animated Text`. 

Reference - https://github.com/aagarwal1012/Animated-Text-Kit#textliquidfill.

**Comment by awhitford** [comment]
It is there!

https://github.com/aagarwal1012/Animated-Text-Kit/blob/3d017ea9e48aa5ff720b7c3691885aa2aa76e669/example/lib/main.dart#L278-L289
