### ISSUE TITLE
addition in contributing.md

### ISSUE THREAD

**Issue by khareyash05** [aagarwal1012/Animated-Text-Kit#236]
Hi! I would like to add the following in contributing.md-
Difference between GIT and GITHUB
How to clone,fork repository
How to create a branch and then use git push to push to repo
Create a PR
Squash commits in a single issue into one
Updating the forked and local repo as the updations are made in the upstream

**Comment by Sameerkash** [comment]
@khareyash05 Difference between Git and Github is beyond the scope of this project, it already assumes familiarity with such things. 
I personally think only a few lines specifying fork, clone , branch and squash would be slightly valuable, or else better would be to pointing to a source that contains all this content. 

Else this is just redundant information. 

CC to other mentors for their opinion.

**Comment by khareyash05** [comment]
Should I provide u with some screen shots of the file @Sameerkash ?

**Comment by Sameerkash** [comment]
Let's wait for another mentor's opinion 

cc @aagarwal1012 @awhitford

**Comment by SirusCodes** [comment]
@khareyash05 you already opened same here #214 and we still think the same.
