### ISSUE TITLE
Option for TypewriterAnimatedTextkit

### ISSUE THREAD

**Issue by baeharam** [aagarwal1012/Animated-Text-Kit#25]
1. I wanna remove cursor
2. I wanna stop right after finish typing

**Comment by aagarwal1012** [comment]
@baeharam, maybe you can use the `Typer`  for that.

**Comment by baeharam** [comment]
@aagarwal1012 Ok, then How can I two typing animation as successive animations in different positions? Is it possible? I'm just modifying your code to achieve it
