### ISSUE TITLE
Missing , (Comma) in Documentation Code Example 

### ISSUE THREAD

**Issue by viralvaghela** [aagarwal1012/Animated-Text-Kit#252]
Inside documentation code of **Rotate** and **Typer** there is missing , (comma) before the onTap() method.

```dart
return SizedBox(
  width: 250.0,
  child: DefaultTextStyle(
    style: const TextStyle(
      fontSize: 30.0,
      fontFamily: 'Bobbers',
    ),
    child: AnimatedTextKit(
      animatedTexts: [
        TyperAnimatedText('It is not enough to do your best,'),
        TyperAnimatedText('you must know what to do,'),
        TyperAnimatedText('and then do your best'),
        TyperAnimatedText('- W.Edwards Deming'),
      ]
      onTap: () {
        print("Tap Event");
      },
    ),
  ),
);
```
I would like to send PR and fix this small issue!

**Comment by SirusCodes** [comment]
How this will add value to the project? Anyone who I taking code from readme can update it on their side.
I don't think there is a need to open a PR for just this thing.
Thanks for raising this issue we can add this in the next update.

**Comment by awhitford** [comment]
#261 resolved this.
