### ISSUE TITLE
Because of colorized text the production app is showing white screen

### ISSUE THREAD

**Issue by dhruv1710** [aagarwal1012/Animated-Text-Kit#258]
The app is working fine in app but in web it is showing white screen and in console it is saying :-
** Another exception was thrown: Instance of 'minified:hW<void>'**

I checked the app and came down to the conclusion.

**Comment by awhitford** [comment]
@dhruv1710 Please provide a reproducible test case because the Colorize animation seems to work fine for the [live example app](https://animated-text-kit.web.app/).
