### ISSUE TITLE
Animate from right to left

### ISSUE THREAD

**Issue by pbouttier** [aagarwal1012/Animated-Text-Kit#26]
Hi,

Would it be possible to have the animated text from right to left ? 

I want to use it to show my users it's possible to slide from right to left, and a animation like that could be nice to show that feature. I use it with colorize right now.

Thanks in advance,

**Comment by aagarwal1012** [comment]
@pbouttier, this issue is a duplicate of #16.
Therefore, I am closing this issue. Contributions are welcomed! 😄
