### ISSUE TITLE
Add Leading Text and Following Text support

### ISSUE THREAD

**Issue by mohamadbastin** [aagarwal1012/Animated-Text-Kit#275]
It would be good to have a way to use the animations in line with other text. or to declare a leading text and a following text.

something like:  "Hello [animated text], good morning!"

I think this could be easily done by putting the texts in a row.

**Comment by aagarwal1012** [comment]
You can do this easily with the `Text`, `AnimatedText`, and `Text` widgets inside a `Row` widget. Closing this issue for now.
