### ISSUE TITLE
Request to add product in Start Flutter

### ISSUE THREAD

**Issue by maheshwari-1153** [aagarwal1012/Animated-Text-Kit#30]
Hello,

I am Maheshwari from team GeekyAnts. On behalf of Start Flutter, we add open source products which we find helpful to the community & also we provide credits to author itself.

Let me know if you are interested showcase your product in our open source website.

Looking forward to hear from you.

**Comment by aagarwal1012** [comment]
@maheshwari-1153, 
Thanks, I would be glad if you include this flutter package on your website.
