### ISSUE TITLE
Pause at end of each text

### ISSUE THREAD

**Issue by mikecbone** [aagarwal1012/Animated-Text-Kit#32]
When using TyperAnimatedTextKit, the end of the text animation feels a little rushed as the full text is only displayed for a fraction of second before the next text animation starts (unless you set a high duration which isn't really a solution).

It would be helpful to have an additional argument that adds a delay in ms to the end of each text animation, before starting the next text. 

I have tried adding zero-width characters to the end of my text to pad out the timing but this shifts the text to the left slightly (when alignment = centre) so it isn't a good long term solution, besides the fact it feels hacky as it is.

**Comment by aagarwal1012** [comment]
@mikecbone, thanks for pointing this feature in this issue. 
Hope that this issue will get resolved soon.

**Comment by aagarwal1012** [comment]
@mikecbone, v2.0.0 solves this issue.
