### ISSUE TITLE
Fade animation speed 

### ISSUE THREAD

**Issue by Hafsa-Awan** [aagarwal1012/Animated-Text-Kit#321]
how to slow down fading of text.

**Comment by raminmoharrami** [comment]
for FadeAnimatedText using duration property:
`                  FadeAnimatedText(
                    'Some Text',
                    duration: Duration(milliseconds: 500),
                  ),`
for TyperAnimatedText using speed property:
`TyperAnimatedText(
                    'Some Text',
                    textStyle: GoogleFonts.lobster(
                      fontSize: 20,
                      color: Colors.grey.shade800,
                    ),
                    speed: Duration(milliseconds: 160),
                  ),`
and etc..(check the property for each animation type)

**Comment by raminmoharrami** [comment]
> how to slow down fading of text.
for FadeAnimatedText using duration property:
` FadeAnimatedText( 'Some Text', duration: Duration(milliseconds: 500), ),`
for TyperAnimatedText using speed property:
`TyperAnimatedText( 'Some Text', textStyle: GoogleFonts.lobster( fontSize: 20, color: Colors.grey.shade800, ), speed: Duration(milliseconds: 160), ),`

for FadeAnimatedText using duration property:
                  FadeAnimatedText( 'Some Text', duration: Duration(milliseconds: 500), ),
for TyperAnimatedText using speed property:
TyperAnimatedText( 'Some Text', textStyle: GoogleFonts.lobster( fontSize: 20, color: Colors.grey.shade800, ), speed: Duration(milliseconds: 160), ),
and etc..(check the property for each animation type)

**Comment by SivaRamana-H-V** [comment]
### Hay Kindly assign this issue to me
