### ISSUE TITLE
How to play and stop animation?

### ISSUE THREAD

**Issue by abhijeets06** [aagarwal1012/Animated-Text-Kit#34]
im newbie please guide :)

1. how to stop animating on load?
2. how to play and stop animation from FloatingActionButton? 
please check image for code reference 
[imgur-img-link](https://imgur.com/a/RLLovpt)

**Comment by aagarwal1012** [comment]
@abhijeets06, there is no functionality regarding the stop and start of the animations, it is autonomous in nature.

**Comment by AdamSGit** [comment]
Well customization is key... I would like this feature as well. Do you want a PR ?

**Comment by aagarwal1012** [comment]
@AdamSGit, It will be awesome if you make a PR. Thanks!

**Comment by AdamSGit** [comment]
I'm on it bro ;)
Thing is, the draft I'm working on is simpler and more powerful, but it imply to replace the total duration parameter with two new ones :
 - **speed** *which is the duration of each character*
 - **pauseDuration** *which is pause duration between each texts*

Those changes would give the power to play complexes sequences. But as it is a breaking change, you will need to wait for the next major release (2.0.0), or precipitate it,  to merge them.

Is that okay for you ?

Cheers,

**Comment by aagarwal1012** [comment]
@AdamSGit, that will surely work, thanks 👍

**Comment by AdamSGit** [comment]
Hi again mate, here is the PR.

Paradoxically, this PR doesn't address the initial issue #34. Being able to pause or play the typer from another widget event would be overkill, given how dart handle that. But it should be pretty easy to create you class extended from the typer class and implement it with the event system you chose.

**Comment by aagarwal1012** [comment]
@AdamSGit, thanks for the update, please check my comment in your PR.

**Comment by aagarwal1012** [comment]
@abhijeets06, v2.0.0 solves this issue.
