### ISSUE TITLE
Add Animated-Text-Kit to Flutter Arsenal

### ISSUE THREAD

**Issue by flutter-arsenal** [aagarwal1012/Animated-Text-Kit#35]
Animated-Text-Kit can be added to FlutterArsenal to help with reach, accessibility and ease-of-use. [Flutter Arsenal](https://flutterarsenal.com) is a directory that is being curated for Flutter libraries and tool. The best way to do is by creating an issue on [github](https://github.com/flutterarsenal/FlutterArsenal/issues/new/choose).

**Comment by aagarwal1012** [comment]
@flutter-arsenal why not you create the issue on your own?

**Comment by karx** [comment]
I took it up. 
@flutter-arsenal generated this issue as part of FlutterArsenal awareness drive. It's an automated bot.

https://github.com/flutterarsenal/FlutterArsenal/issues/58
Cheers.

**Comment by aagarwal1012** [comment]
@karx thank buddy! 👍
