### ISSUE TITLE
Updating the new incoming text values through didUpdateWidget lifeCycle

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [aagarwal1012/Animated-Text-Kit#39]

**Comment by aagarwal1012** [comment]
@AlaaEldeenYsr, can you please add some description for this issue?

**Comment by AlaaEldeenYsr** [comment]
The problem is when i setState to change the text value which is passed to
the Animated text widget that widget doesn't replace the incoming new text
value with the old one. But what happened that both float on each others
and that's because you are using stateFullWidget

here is the the tow cases
first video is without using the AnimatedTextKit
second one is with using the AnimatedTextKit
