### ISSUE TITLE
Restart animations OR delay between repetitions

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#43]
When using `isRepeatingAnimation: false`, it would be nice to be able to programmatically restart the animation(s).  (I'm thinking maybe a response to a tap.)

I'm not an expert, but perhaps exposing [AnimationController](https://api.flutter.dev/flutter/animation/AnimationController-class.html) would help?

An alternative solution would be to specify an additional `Duration` that represents the delay between animation repetitions.  My animation takes 9 seconds, for example.  Imagine I said, delay 60 seconds before repeating.

**Comment by aagarwal1012** [comment]
@awhitford, v2.0.0 solves this issue.

**Comment by awhitford** [comment]
I don't see how v2.0.0 solves this issue.

I see that `totalRepeatCount` was introduced, but I don't see a way to control the `pause` _between repeats_.
