### ISSUE TITLE
RotateAnimatedTextKit not centering

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#44]
Consider the following code:
```dart
      Column(children: [
        Image.asset(
          'images/welcome.jpg',
        ),
        Expanded(
          child: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                RotateAnimatedTextKit(
                  duration: Duration(seconds: 9),
                  text: ['one', 'two', 'three'],
                  textStyle: animatedTextStyle,
                  isRepeatingAnimation: false,
                ),
              ],
            ),
          ),
        ),
      ]),
```
The text appears on the left rather than being centered, despite being a child of `Center` and `Expanded`.

If I replace the `RotateAnimatedTextKit` with `FadeAnimatedTextKit`, then the text is centered as expected.

To center `RotateAnimatedTextKit`, I need to wrap it in a `Row` with `mainAxisAlignment: MainAxisAlignment.center`, but I would expect that to be unnecessary.

Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-US) and Dart 2.5.0.

**Comment by adilsachwani** [comment]
I am facing the same issue as reported.

**Comment by AadumKhor** [comment]
@awhitford the widget `RotateAnimatedTextKit` has an alignment parameter that you can specify. That way you do not need to use `Center`.

**Comment by yashank09** [comment]
Hello devs! Thanks for this easy to use lifesaver! I'm using RotateAnimatedText with a column with cross axis center. This is making the static text centered but the RotateText will not center even with alignment or textAlign properties. 
Also for some reason, the default code of alignment: AlignmentDirectional.topStart is giving me an error. Any ideas?

**Comment by yashank09** [comment]
Sorry for some reason alignment property 'centerRight' did the job.. Not sure if this is expected behavior but we can close this :) 
`
  Column(
                  children: <Widget>[
                    Text(
                      "Text",
                      style: TextStyle(fontSize: 43.0),
                    ),
                    RotateAnimatedTextKit(
                      alignment: Alignment.centerRight,
                      repeatForever: true,
                      text: ["AWESOME", "OPTIMISTIC", "DIFFERENT"],
                      textStyle:
                          TextStyle(fontSize: 40.0, fontFamily: "Horizon"),
                    ),
                  ],
                ),
`

**Comment by taxon-hub** [comment]
> Sorry for some reason alignment property 'centerRight' did the job.. Not sure if this is expected behavior but we can close this :)
> `Column( children: <Widget>[ Text( "Text", style: TextStyle(fontSize: 43.0), ), RotateAnimatedTextKit( alignment: Alignment.centerRight, repeatForever: true, text: ["AWESOME", "OPTIMISTIC", "DIFFERENT"], textStyle: TextStyle(fontSize: 40.0, fontFamily: "Horizon"), ), ], ),`

it worked.................!
