### ISSUE TITLE
onTap event on List of item in a Text

### ISSUE THREAD

**Issue by rajeevjaiswal** [aagarwal1012/Animated-Text-Kit#5]
@aagarwal1012 Can I get onTap event to the list that is passed to the Text Widget?

**Comment by aagarwal1012** [comment]
@rajeevjaiswal sure, I will add this feature to the text widget. Thanks for pointing the feature 👍 😄

**Comment by rajeevjaiswal** [comment]
@aagarwal1012 Does this returns the text that was clicked or just a tap event?

**Comment by rajeevjaiswal** [comment]
As the widget takes list of string, I believe you can give the index of the tapped text. 
Another thing if possible please also provide animation of text like from right to left, left to right

**Comment by rajeevjaiswal** [comment]
@aagarwal1012 No issues. Can you guide me what should I change to get position as callback when  onTap is triggered

**Comment by aagarwal1012** [comment]
@rajeevjaiswal I think that feature "get position on callback" is not useful for this package as this package is meant only for the UI part.
Also I have added some more text animations that could be implemented under the **Projects** section of this repository. You can work on them or you can propose some other ideas that can be useful for this repository...

**Comment by aagarwal1012** [comment]
@rajeevjaiswal I think that the feature that you want is not possible in the way I have implemented the animation part because I have used **stack** and put different text widget one over another and make all the animations work. If you find the one to resolve this issue then tell me.
