### ISSUE TITLE
Bug: calling containsKey on string

### ISSUE THREAD

**Issue by sgehrman** [aagarwal1012/Animated-Text-Kit#51]
Run the example app, enable break on all exceptions.

A bunch of places in the code call:
      if (!widget.text[i].containsKey('text')) throw Error();

containsKey is not a function on String.  Maybe you meant to use _texts?

**Comment by sgehrman** [comment]
Add strict linting and clean up your code with analyis_options.yaml file.  You'll probably find other errors.

**Comment by recapnrelax** [comment]
I'm also seeing this issue.

**Comment by AadumKhor** [comment]
@sgehrman I have added a type check in #82 to ensure it is not called on a string. Please check and update if you see any other issue with it.

**Comment by aagarwal1012** [comment]
@sgehrman, we have pushed a new version named `v2.2.0` of animated text kit that solves this issue. Please check and feel free to reopen it if any problem arises.
