### ISSUE TITLE
Show last text

### ISSUE THREAD

**Issue by awhitford** [aagarwal1012/Animated-Text-Kit#55]
I recently upgraded to v2.0.0 and now my text animations behave differently than they used to.  Sure, I had to adjust the `duration` due to the breaking change -- not a big deal.  However, the `RotateAnimatedTextKit` and `FadeAnimatedTextKit` used to show the last text item when it was done.  Now, it rotates or fades away too, leaving a blank area of the screen.

Is there a way to get the old behavior with 2.x?

**Comment by emanuel-braz** [comment]
same here

**Comment by rashmisridar** [comment]
same problem with me also @awhitford, @emanuel-braz found any solution

**Comment by emanuel-braz** [comment]
> same problem with me also @awhitford, @emanuel-braz found any solution

Downgrade to v1.3.1

**Comment by rashmisridar** [comment]
Thank You

**Comment by rashmisridar** [comment]
For my need have to repeat the count 3 times after that need to show normal text so made isRepeatingAnimation: false ,used the onFinished method added the boolean value . 
Below is the code snippet


`ScaleAnimatedTextKit(
                                                          totalRepeatCount: 3,
                                                          isRepeatingAnimation: false,
                                                          onFinished: ()=>{
                                                            setState(()=>{
                                                              mCarNameAnimFinish =true

                                                            }),
                                                          },
                                                          text: [
                                                            "Welcome to flutter",
                                                          ],
                                                          textStyle: TextStyle(
                                                              color: Constant.white,
                                                              fontSize: mCarNameAnimFinish?12.0:20.0,
                                                              fontFamily: "Canterbury"
                                                          ),
                                                          textAlign: TextAlign.start,
                                                          alignment: AlignmentDirectional.topStart // or Alignment.topLeft
                                                      `

**Comment by rashmisridar** [comment]
> > same problem with me also @awhitford, @emanuel-braz found any solution
> 
> @rashmisridar Downgrade to v1.3.1

Thank You
