### ISSUE TITLE
Use of Center or Padding messes up with ColorizeAnimatedTextKit

### ISSUE THREAD

**Issue by dekadevelop** [aagarwal1012/Animated-Text-Kit#56]
**Describe the bug**
If I try to adjust ColorizeAnimatedTextKit with padding in a 3 words string, the animation does a run in the first row and then, starts again for the full string.

**To Reproduce**
```
Center( // or Padding
      child: ColorizeAnimatedTextKit(
          text: [
            "My three words",
          ],
          textStyle: GoogleFonts.dosis(
            fontSize: 38,
            fontWeight: FontWeight.w800,
          ),
          colors: [
            Colors.purple,
            Colors.blue,
            Colors.yellow,
            Colors.red,
          ],
          textAlign: TextAlign.center,
          alignment: AlignmentDirectional.topStart 
          ),
    );
  }
```

**Comment by AadumKhor** [comment]
@dekadevelop I am not sure what behavior you are expecting since you haven't mentioned it. I would really appreciate it if you specify exactly what you're looking for from the widget.
