### ISSUE TITLE
Duration property

### ISSUE THREAD

**Issue by Mehdi-orang** [aagarwal1012/Animated-Text-Kit#63]
I'm getting error when i want to set duration in TypewriterAnimatedTextKit() object.

The named parameter 'duration' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'duration'.dart(undefined_named_parameter)

**Comment by danniescull** [comment]
You need to use 'speed' instead of 'duration'.

**Comment by AadumKhor** [comment]
@Mehdi-orang there is no duration property in `TypewriterAnimatedTextKit`, it is named `speed` because it helps control the speed of the animation.

**Comment by AadumKhor** [comment]
Closing this issue since there is no feedback. Feel free to reopen if and when needed.
