### ISSUE TITLE
when i use TypewriterAnimatedTextKit it is vary fast how to make it slowly

### ISSUE THREAD

**Issue by mohmedAK** [aagarwal1012/Animated-Text-Kit#69]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AadumKhor** [comment]
@mohmedAK you can use the speed parameter and specify the time of the animation.

**Comment by AadumKhor** [comment]
Closing this issue since there is no feedback. Feel free to reopen if and when needed.

**Comment by mohmedAK** [comment]
Thanks for help
