### ISSUE TITLE
RotateAnimatedTextKit Animation and Infinity Repetition Bug

### ISSUE THREAD

**Issue by plcpinho** [aagarwal1012/Animated-Text-Kit#71]
**Bugs Description**
(1) When using the RotateAnimatedTextKit widget, the rotation animation does not performs as expected. After the 2.0.0 version, the text starts at the top (not at the center) and it is impossible fix this animation problem using some align property. I hope this issue to be fixed once I'd like to use some of the new versions properties such as "pause".

(2) isRepeatingAnimation property is not working. I'd like to repeat the animation infinitively.

**Expected behaviours**
Fluid animation and isRepeatingAnimation = true working like 1.3.1 version.

**Versions**
This bugs only happen in ^2.0.0 versions

**Comment by yiminghan** [comment]
I just opened #72 for infinite animation, please take a look

**Comment by AadumKhor** [comment]
@plcpinho The `RotateAnimatedTextKit` is not supposed to start from the center. It is supposed to slide in from above to give the effect of rotating. As far as the alignment is concerned we have also updated that. Please check and provide updates.
