### ISSUE TITLE
Feature request: Percentage parameter for TextLiquidFill widget

### ISSUE THREAD

**Issue by CesarPrz** [aagarwal1012/Animated-Text-Kit#75]
**Is your feature request related to a problem? Please describe.**
I wanted to fill up the waves with a parameter for the TextLiquidFill widget, which is not possible.

**Describe the solution you'd like**
Add a `percentage` parameter on the TextLiquidFill 
(After looking at your source code, i think it would be as simple as to replace 
text_liquid_fill.dart:130 ` percentValue: _loadValue.value,`
to 
text_liquid_fill.dart:130 ` percentValue: _percentage ? percentage : _loadValue.value,`

Thank you for your work on this package !

**Comment by aagarwal1012** [comment]
@CesarPrz, can you make a PR for this change?

**Comment by DR-CesarPrz** [comment]
Sure thing, i'll probably push it by the end of the weekend.

**Comment by CesarPrz** [comment]
Sure thing, i'm busy right now but i'll do it this weekend.

**Comment by aagarwal1012** [comment]
@CesarPrz, thanks for the quick response.
