### ISSUE TITLE
TextLiquidFill not showing 

### ISSUE THREAD

**Issue by raymondddenny** [aagarwal1012/Animated-Text-Kit#76]
**Describe the bug**
I was trying using the TextLiquidFill, but it got me error

**Expected behavior**
It show up like the example

**Screenshots**
![1589985373571](https://user-images.githubusercontent.com/42437225/82459579-b2bd5a00-9aea-11ea-9838-d73ddc76431f.jpg)

**Flutter:**
 - version : 1.18.0-11.1.pre
 - channel : beta

**Dart:**
 - version : 3.10.2

**Additional context**
packages/flutter/src/rendering/layer.dart.lib.js 636:12        [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart.lib.js 1212:50       addChildrenToScene
packages/flutter/src/rendering/layer.dart.lib.js 1309:12       addToScene
packages/flutter/src/rendering/layer.dart.lib.js 636:12        [_addToSceneWithRetainedRendering]
packages/flutter/src/rendering/layer.dart.lib.js 1212:50       addChildrenToScene
packages/flutter/src/rendering/layer.dart.lib.js 1723:12       addToScene
packages/flutter/src/rendering/layer.dart.lib.js 1024:12       buildScene
packages/flutter/src/rendering/layer.dart.lib.js 4228:32       compositeFrame
packages/flutter/src/rendering/layer.dart.lib.js 4511:25       drawFrame
packages/flutter/src/widgets/widget_span.dart.lib.js 39783:15  drawFrame
packages/flutter/src/rendering/layer.dart.lib.js 4487:12       [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart.lib.js 721:9       [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart.lib.js 693:37      handleDrawFrame
packages/flutter/src/scheduler/binding.dart.lib.js 611:14      <fn>
dart:sdk_internal 22859:11                                     internalCallback
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by AadumKhor** [comment]
@raymondddenny I used the `TextLiquidFill` code shown in the screenshot and it works fine. Maybe it breaks down in a certain way with the whole widget tree so I would suggest you post the entire code for me replicate.

**Comment by raymondddenny** [comment]
@AadumKhor Thanks for reply, will try recheck my code again first, if still got bug will inform you here. Thanks .
