### ISSUE TITLE
ability to choose between Repeating or play once (Forward)

### ISSUE THREAD

**Issue by OsamaNsr** [aagarwal1012/Animated-Text-Kit#8]
### I'd like to add a simple option to the animation whether it shall repeat or play once.

also if possible, more control of the animation, like stopping it, resume and delay.

this is my very 1st ticket ever so hope it's clear and following the rules.

**Comment by aagarwal1012** [comment]
@OsamaNsr 
I will surely look upon this, if you like to contribute then you can surely make a pull request.
Thanks 👍

**Comment by aagarwal1012** [comment]
@OsamaNsr this issue has been resolved.
Thank you @salihgueler for great work 👍
