### ISSUE TITLE
duration method is not working

### ISSUE THREAD

**Issue by ojasvishaklya** [aagarwal1012/Animated-Text-Kit#89]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by AadumKhor** [comment]
@ojasvishaklya can you describe the issue in detail preferably with the source code?

**Comment by AadumKhor** [comment]
Closing this since there is no feedback.
