### ISSUE TITLE
[Question] How to keep Centered TypewriterAnimatedTextKit from "jumping"

### ISSUE THREAD

**Issue by paxcodes** [aagarwal1012/Animated-Text-Kit#90]
Because the cursor "blinks" by being added and removed, the text's width visibly "jitters" as it is centred.

![Jun-08-2020 16-49-38](https://user-images.githubusercontent.com/13646646/84090995-17602c00-a9a8-11ea-99ca-480e3f63574e.gif)

Is there a way I can centre the TypewriterAnimatedTextKit without the text-width from "jumping"? 

If I change the package's behaviour of "deleting" the underscore, does this package allow customization of the behaviour** of TypewriterAnimatedTextKit? If not, would this package be open to a PR?

** I wonder if instead of the underscore/cursor being deleted, it would be "replaced" by a whitespace character. If I then set my font to monospace, I imagine the width wouldn't "jump"

**Comment by paxcodes** [comment]
Looks like https://github.com/aagarwal1012/Animated-Text-Kit/pull/85 solves this.

**Comment by snj07** [comment]
What's the plan of pushing this change to pub.dev? I don't see this fix in `2.2.0`? Please let us know the plans.
