### ISSUE TITLE
Can we get same effects on Icons as well?

### ISSUE THREAD

**Issue by harnarayans** [aagarwal1012/Animated-Text-Kit#94]
I like various animation effects on Text that are part of this package.
I think it would be wonderful if you could extend these animations for Icons as well.
Just imagine a glass icon with LiquidFill animation.

**Comment by AadumKhor** [comment]
@harnarayans Thanks for your suggestion. We have a similar request made in #92 and will surely update the package accordingly. Closing this issue here. Will update this thread once the features are in.
